### ISSUE TITLE
Make User object transformable

### ISSUE THREAD

**Issue by schibsted-rafal-adamek** [schibsted/account-sdk-android#35] opened 2018-03-16 13:57 UTC
Our architecture is designed to be decoupled as much as possible from the platform specific code. We use MVP architecture for our presentation layer. Our presenters have no Android dependencies and views are kept as simple as possible.

Integrating with `account-sdk` creates some challenges with this architecture though.

`User` object received from `PasswordActivity` is a `Parcelable` object that can call network on its own. Because of its heavy Android dependencies and no base class we can’t easily pass it around between our layers (as we can't have android dependencies inside presenters)

There are couple of improvements we can see on this matter.

- Make `User` object recreateable. We can easily pass our custom objects around if we could map them to the actual SPiD user object. Right now `User` is created using a `TokenResponse` but we can’t access its contents to create a different object because it’s a) not marked as val, b) is marked as internal.  If the Token object was exposed along with all necessary user properties we could easily transoform it with our objects.

- Expose `User` object methods outside (like fetching the details) with userId/token as parameters so we could call the methods without having the full `User` object.

Or any other ideas?

**Comment by Nexcius** [comment] 2018-03-19 13:31
Hi Rafal

Unfortunately, we cannot provide the token. This is by design to avoid that they get leaked. If being compliant with MVP is your concern, I have a suggestion which I'd like to run you by.

We can make the `User` object not parcelable, meaning you can safely have it in your presenters. We'll keep the APIs etc in there and instead provide a wrapper for that class to have it parcelable. 

Do you think that approach would work for you?

**Comment by schibsted-rafal-adamek** [comment] 2018-03-20 11:45
Hi,

Thanks for the reply. If it's not much work for you then yes, that would be useful. I understand you cannot expose the `Token` object, although I must say that would be the easiest for us.

There's also `import android.support.annotation.WorkerThread` annotation in the `User` object. I'm not sure how can you tackle that.

**Comment by Nexcius** [comment] 2018-03-21 14:13
Hello again Rafal

I have an implementation for this now. When I was applying this to the example app, I realized that it adds a lot of unneeded stuff to the code. As I'm now wrapping the `User` object in `UserParcel`, I need to pass the latter around then get the user object from that one.

Could you please explain to me why you cannot pass the `User` object around? If this is for testing, it causes no problems as no Android functionality is called. This is fully compatible with JUnit. For your app, we're not implying any additional dependencies as all of this is part of the standard library.

Applying these changes will reduce the developer experience, something which we care a lot about. We're willing to make the changes, but to do so we need a good reason. Looking forward to your response.

**Comment by Nexcius** [comment] 2018-03-22 14:17
I'm closing this for now. Please let us know if this ends up being an issue

**Closed by Nexcius** 2018-03-22 14:17 UTC
Labels: Type: Enhancement, Type: Request
