### ISSUE TITLE
Smart lock not working

### ISSUE THREAD

**Issue by lar-vik** [schibsted/account-sdk-android#401] opened 2019-08-21 11:25 UTC
### Summary
Smart lock not working

### Environment
- SDK Version: 1.7.2
- SDK Module: ?
- Android Version: 9
- Device Info: Samsung S9 & Huawei P20

### Details
No matter what account I pick I'll end upp at the login screen. I also tried to add the app in Smart Lock setting as "Never save"

Log:
RequiredConfiguration: Your host is not correct, deep links might fail, please provide a complete host
DeepLinkHandler: Received null value deep link. Not performing any actions
Navigation: a dialog is already shown
SmartlockController: cannot silently log-in, providing the account identifier
SmartlockController: Resolving: 
com.google.android.gms.common.api.ResolvableApiException: 4: Sign-in required..message with requestCode 4
EmailIdentificationFragment: Attempting to prefill  email
EmailIdentificationFragment: email wasn't found

![Screenshot_20190821-112426_Google_Play_services](https://user-images.githubusercontent.com/54353929/63427832-65567400-c416-11e9-8c14-c467c94fcd8c.jpg)
![Screenshot_20190821-112431_Blocket](https://user-images.githubusercontent.com/54353929/63427835-6a1b2800-c416-11e9-90c9-a24fb3bb3186.jpg)

**Comment by sa-mao** [comment] 2019-08-26 12:19
I couldn't reproduce this on the demo app. Could you try version 1.8.0?

**Comment by lar-vik** [comment] 2019-08-27 07:38
Hi, I tried 1.8.0 with same behaviour. A colleague also tried on OnePlus 5 (android 9.0.8) with same behaviour.

**Comment by sa-mao** [comment] 2019-08-27 12:56
Could it be that you don't have a stored password for that account? if so this PR #404  fixes it.

**Comment by lar-vik** [comment] 2019-08-28 09:30
I haven't managed to clear Smart Lock so I'm not sure if the password is saved. If it's not saved that PR could solve that case. I get the same behaviour on all accounts

**Comment by lar-vik** [comment] 2019-08-29 06:56
I have managed to clear Smart Lock and verified that the feature works as intended if I save the passwords for my accounts. 

The initial issue I had must have been that the password was not saved and that the email was not copied into the email field and hopefully the PR #404 will fix it. Thank you.

**Comment by sa-mao** [comment] 2019-08-29 17:44
Let close this as #404 is already merged. Feel free to reopen if needed.

**Closed by sa-mao** 2019-08-29 17:44 UTC
Labels: Status: Acknowledged
